### ISSUE TITLE
Has checkpoint been released yet?

### ISSUE THREAD

**Issue by wangqian621** [prompteus/audio-captioning#3]
Thanks for great work!

**Comment by prompteus** [comment]
Hi @wangqian621,

Yes! We have released several trained checkpoints and a preprint describing our experiments :)

The checkpoints are on Huggingface - [Whisper for audio captioning](https://huggingface.co/collections/MU-NLPC/whisper-for-audio-captioning-653fc8f8fd9b567733359593)

The preprint is on Arxive: https://arxiv.org/abs/2305.09690

If you find our work useful, please cite us as:

```
@misc{kadlčík2023whisper,
      title={A Whisper transformer for audio captioning trained with synthetic captions and transfer learning}, 
      author={Marek Kadlčík and Adam Hájek and Jürgen Kieslich and Radosław Winiecki},
      year={2023},
      eprint={2305.09690},
      archivePrefix={arXiv},
      primaryClass={cs.SD}
}
```

**Comment by prompteus** [comment]
I have updated the readme to reference the checkpoints and the technical report.

**Comment by wangqian621** [comment]
Thanks， that’s helpful~
