### ISSUE TITLE
Can't do inference using transformers >= 4.40

### ISSUE THREAD

**Issue by cahya-wirawan** [prompteus/audio-captioning#4]
Hi,

Thanks a lot for the great repo. We use it to train whisper-tiny with other captioning dataset. The inference runs well 
with transformers up to version 4.36, but doesn't work anymore from version 4.40 to the latest version is 4.47.
It seems there are several breaking changes in between around the forced_decoder_ids functionality. Would you be able 
to update the repo to have it working in the latest transformers? Thanks a lot.

**Comment by prompteus** [comment]
Hi,
I'm glad my repo is useful to you :) 

Unfortunately, I don't have the capacity to update the repo. However, it is likely that the issue was already resolved on the HuggingFace repo of one of our trained models: 
https://huggingface.co/MU-NLPC/whisper-small-audio-captioning/discussions/5

If that's the case, the updated model code is here:
https://huggingface.co/MU-NLPC/whisper-small-audio-captioning/blob/main/model_class.py

If you check that it solves your problem, and send a PR here, I will happily accept it.

**Comment by cahya-wirawan** [comment]
Great, I will try the solution and let you know the result. Thanks.

**Comment by cahya-wirawan** [comment]
Hi,
The patch works up to transformers version 4.42. But doesn't work anymore after that version. Following is the error message in version 4.47:
```
The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Traceback (most recent call last):
  File "/Users/cahya/Work/MachineLearning/audio-captioning/inference_test.py", line 31, in <module>
    outputs = model.generate(
  File "/Users/cahya/Work/MachineLearning/audio-captioning/audiocap/models.py", line 152, in generate
    return super(transformers.WhisperPreTrainedModel, self).generate(   # changed by adam (calling grandparent)
  File "/Users/cahya/miniconda3/envs/transformers/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/cahya/miniconda3/envs/transformers/lib/python3.10/site-packages/transformers/generation/utils.py", line 2145, in generate
    prepared_logits_processor = self._get_logits_processor(
  File "/Users/cahya/miniconda3/envs/transformers/lib/python3.10/site-packages/transformers/generation/utils.py", line 1033, in _get_logits_processor
    raise ValueError(
ValueError: You have explicitly specified `forced_decoder_ids`. Please remove the `forced_decoder_ids` argument in favour of `input_ids` or `decoder_input_ids` respectively.
```

**Comment by prompteus** [comment]
I looked into the issue and found a solution. 

It's already merged into the main branch, as no breaking changes were necessary. It seems to be compatible with both the locked version (4.27.1) and the newest transformer release for macOS, which is 4.46.3 at the moment.

@cahya-wirawan, please let me know if the updated version works as expected in your use case.

**Comment by cahya-wirawan** [comment]
Cool, thanks a lot, I will test it and let you know the result again

**Comment by cahya-wirawan** [comment]
Hi, thanks for the fix. It works for transformers version 4.27.1 and also 4.46.3 (in MacOS). I tried also the latest version 4.47.1, there was a strange error message:
```
...
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```
But after I add "if __name__ == '__main__':" in my test script, it works without any problem. So I would say the issue has been solved. Thanks again. 
I want also to do  training with the newer transformers, because it seems the training with newer transformer is much faster than with the version 4.27.1.

**Comment by prompteus** [comment]
That's interesting, both `predict.py` and `train_whisper_supervised.py`
already contain `if __name__ == '__main__'`

where specifically did you have to add it?

**Comment by cahya-wirawan** [comment]
Sorry, I have my own simple test script where I just put everything in global scope:
```
import transformers
from transformers import WhisperProcessor, WhisperForConditionalGeneration
from pathlib import Path
import audiocap
import librosa

audio_dir = Path("data/clotho_v2.1/audiofolder")
architecture_name = "MU-NLPC/whisper-tiny-audio-captioning"
print(f"Trasformer version: {transformers.__version__}")
tokenizer = transformers.WhisperTokenizer.from_pretrained(architecture_name, language="en", task="transcribe")
model = audiocap.WhisperForAudioCaptioning.from_pretrained(architecture_name)
feature_extractor = transformers.WhisperFeatureExtractor.from_pretrained(architecture_name)

input_file = audio_dir/"woodpecker1.wav"
audio, sampling_rate = librosa.load(input_file, sr=feature_extractor.sampling_rate)
features = feature_extractor(audio, sampling_rate=sampling_rate, return_tensors="pt").input_features

# Prepare caption style
style_prefix = "clotho > caption: "
style_prefix_tokens = tokenizer("", text_target=style_prefix, return_tensors="pt", add_special_tokens=False).labels

model.eval()
outputs = model.generate(
    inputs=features,
    forced_ac_decoder_ids=style_prefix_tokens,
    max_length=100,
)
print(f"output: {tokenizer.batch_decode(outputs)}")
```

It works actually up to 4.46.3, but not anymore in >= 4.47.0. So I put the code above in a main function and call it in 
`if __name__ == '__main__'`

Your predict.py and train_whisper_supervised.py should just work I think

**Comment by prompteus** [comment]
Ok, it seems like Transformers 4.47 introduces some kind of parallelism that requires it.

Anyway, it seems like this issue is resolved. Feel free to reopen it if you find any problems with the current version.

**Comment by cahya-wirawan** [comment]
Just a short info, the training fails after this fix has been introduced
